### ISSUE TITLE
ModuleDeployableAntennas

### ISSUE THREAD

**Issue by deimos790** [deimos790/BoxSat_Continued#2]
convert to...

**Comment by Kerbas-ad-astra** [comment]
You can open the model files in a text editor to find the names of transforms to give pivotName.  As a rule of thumb, look for a "directory"-looking thing (i.e. names separated by slashes) and then pick the first name out of the list.  So, for Antenna_Tape2, you can see several instances of "Antenna_Tape_Shield004/Antenna_tape004" in the file, so set pivotName = Antenna_Tape_Shield004.  Likewise, Dish_Boom for the hinged dish and Antenna_Tape_Shield for Antenna_Tape1.  Maybe also give the tape antennas -- or at least the single-tape antenna -- high resistance values, since they're very mechanically simple?  That would give them a good niche.
